name: Hexo Deploy to Github Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install Dependencies
        run: npm install

      - name: Install Hexo
        run: npm install -g hexo-cli

      - name: Generate Static Files
        run: hexo generate

      - name: Checkout Sudoku Code
        uses: actions/checkout@v4
        with:
          repository: FanBB2333/G-thesis
          path: sudoku-source
          sparse-checkout: temp4/web

      - name: Build Sudoku Project
        working-directory: sudoku-source/temp4/web
        run: |
          npm install
          npm run build

      - name: Move Sudoku to Public
        run: |
          mkdir -p public/sudoku
          cp -r sudoku-source/temp4/web/out/* public/sudoku/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages  # default: gh-pages
          publish_dir: ./public